# Form implementation generated from reading ui file 'main_window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from __future__ import annotations

from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWebEngineWidgets
from PyQt5 import QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(1133, 787)
        MainWindow.setStyleSheet('')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet('background: rgba(50,50,50,0.5)')
        self.centralwidget.setObjectName('centralwidget')
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName('gridLayout')
        self.frame_main_body = QtWidgets.QFrame(self.centralwidget)
        self.frame_main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_body.setObjectName('frame_main_body')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_main_body)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_main_body)
        self.stackedWidget.setObjectName('stackedWidget')
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName('home_page')
        self.gridLayout_4 = QtWidgets.QGridLayout(self.home_page)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName('gridLayout_4')
        self.frame_input = QtWidgets.QFrame(self.home_page)
        self.frame_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input.setObjectName('frame_input')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_input)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.fr_main_functions = QtWidgets.QFrame(self.frame_input)
        self.fr_main_functions.setMinimumSize(QtCore.QSize(0, 0))
        self.fr_main_functions.setMaximumSize(QtCore.QSize(355, 16777215))
        self.fr_main_functions.setStyleSheet(
            'background-color: rgba(0,0,0,0.7)\n'
            '',
        )
        self.fr_main_functions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_main_functions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_main_functions.setObjectName('fr_main_functions')
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fr_main_functions)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName('verticalLayout_6')
        self.frame_avatar = QtWidgets.QFrame(self.fr_main_functions)
        self.frame_avatar.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_avatar.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_avatar.setObjectName('frame_avatar')
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_avatar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.label_avatar = QtWidgets.QLabel(self.frame_avatar)
        self.label_avatar.setStyleSheet(
            '#label_avatar {\n'
            '    background-color: white;  /* Màu nền trắng */\n'
            '}\n'
            '',
        )
        self.label_avatar.setText('')
        self.label_avatar.setPixmap(
            QtGui.QPixmap(
                'E:/Qt_Designer/fire_alarm_system.jpg',
            ),
        )
        self.label_avatar.setScaledContents(True)
        self.label_avatar.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avatar.setObjectName('label_avatar')
        self.horizontalLayout_5.addWidget(self.label_avatar)
        self.verticalLayout_6.addWidget(self.frame_avatar)
        self.frame_file_path = QtWidgets.QFrame(self.fr_main_functions)
        self.frame_file_path.setStyleSheet(
            'QFrame#frame_file_path\n'
            '{\n'
            '    color: white;\n'
            '    border-radius: 15px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            '',
        )
        self.frame_file_path.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file_path.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file_path.setObjectName('frame_file_path')
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_file_path)
        self.gridLayout_9.setObjectName('gridLayout_9')
        self.le_cam_path = QtWidgets.QLineEdit(self.frame_file_path)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_cam_path.setFont(font)
        self.le_cam_path.setStyleSheet(
            'background: rgba(255,255,255,0.95);\n'
            'border: 2px solid white;',
        )
        self.le_cam_path.setObjectName('le_cam_path')
        self.gridLayout_9.addWidget(self.le_cam_path, 0, 0, 2, 2)
        self.frame_4 = QtWidgets.QFrame(self.frame_file_path)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName('frame_4')
        self.btn_choose_path = QtWidgets.QPushButton(self.frame_4)
        self.btn_choose_path.setGeometry(QtCore.QRect(60, 0, 200, 34))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_choose_path.sizePolicy().hasHeightForWidth(),
        )
        self.btn_choose_path.setSizePolicy(sizePolicy)
        self.btn_choose_path.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_choose_path.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_choose_path.setFont(font)
        self.btn_choose_path.setStyleSheet(
            'QPushButton#btn_choose_path\n'
            '{\n'
            '   background-color: rgba(255,255,255,0.4);\n'
            '    color: white;\n'
            '    border-radius: 5px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            'QPushButton:hover#btn_choose_path\n'
            '{\n'
            '   background-color: orange\n'
            '}\n'
            'QPushButton:pressed#btn_choose_path\n'
            '{\n'
            '    background-color: white;\n'
            '    color: black;\n'
            '    padding-left: 5px;\n'
            '    padding-top: 5px;\n'
            '}\n'
            '',
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/folder_icon.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_choose_path.setIcon(icon)
        self.btn_choose_path.setIconSize(QtCore.QSize(26, 30))
        self.btn_choose_path.setObjectName('btn_choose_path')
        self.gridLayout_9.addWidget(self.frame_4, 2, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.frame_file_path)
        self.frame_buttons = QtWidgets.QFrame(self.fr_main_functions)
        self.frame_buttons.setStyleSheet(
            'QFrame#frame_buttons\n'
            '{\n'
            '    color: white;\n'
            '    border-radius: 15px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            '',
        )
        self.frame_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons.setObjectName('frame_buttons')
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_buttons)
        self.verticalLayout_3.setObjectName('verticalLayout_3')
        self.frame_btn_1 = QtWidgets.QFrame(self.frame_buttons)
        self.frame_btn_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_1.setObjectName('frame_btn_1')
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btn_1)
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.btn_start = QtWidgets.QPushButton(self.frame_btn_1)
        self.btn_start.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_start.setFont(font)
        self.btn_start.setStyleSheet(
            'QPushButton#btn_start\n'
            '{\n'
            '    background-color: rgba(255, 255, 255, 0.4);\n'
            '    color: white;\n'
            '    border-radius: 15px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            'QPushButton:hover#btn_start\n'
            '{\n'
            '    background-color: lightgreen;\n'
            '}\n'
            'QPushButton:pressed#btn_start\n'
            '{\n'
            '    background-color: white;\n'
            '    color: black;\n'
            '    padding-left: 5px;\n'
            '    padding-top: 5px;\n'
            '}\n'
            '',
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/start_icon.jpg'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_start.setIcon(icon1)
        self.btn_start.setIconSize(QtCore.QSize(30, 35))
        self.btn_start.setObjectName('btn_start')
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_link_cam = QtWidgets.QPushButton(self.frame_btn_1)
        self.btn_link_cam.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_link_cam.setFont(font)
        self.btn_link_cam.setStyleSheet(
            'QPushButton#btn_link_cam\n'
            '{\n'
            '   background-color: rgba(255, 255, 255, 0.4);\n'
            '    color: white;\n'
            '    border-radius: 15px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            'QPushButton:hover#btn_link_cam\n'
            '{\n'
            '   background-color: red\n'
            '}\n'
            'QPushButton:pressed#btn_link_cam\n'
            '{\n'
            '    background-color: white;\n'
            '    color: black;\n'
            '    padding-left: 5px;\n'
            '    padding-top: 5px;\n'
            '}',
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/exit_icon.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_link_cam.setIcon(icon2)
        self.btn_link_cam.setIconSize(QtCore.QSize(35, 35))
        self.btn_link_cam.setObjectName('btn_link_cam')
        self.horizontalLayout_2.addWidget(self.btn_link_cam)
        self.verticalLayout_3.addWidget(self.frame_btn_1)
        self.frame_btn_2 = QtWidgets.QFrame(self.frame_buttons)
        self.frame_btn_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn_2.setObjectName('frame_btn_2')
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_btn_2)
        self.horizontalLayout_10.setObjectName('horizontalLayout_10')
        self.btn_pause = QtWidgets.QPushButton(self.frame_btn_2)
        self.btn_pause.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pause.setFont(font)
        self.btn_pause.setStyleSheet(
            'QPushButton#btn_pause\n'
            '{\n'
            '    background-color: rgba(255, 255, 255, 0.4);\n'
            '    color: white;\n'
            '    border-radius: 15px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            'QPushButton:hover#btn_pause\n'
            '{\n'
            '    background-color: rgba(224, 195, 30, 1);\n'
            '}\n'
            'QPushButton:pressed#btn_pause\n'
            '{\n'
            '    background-color: white;\n'
            '    color: black;\n'
            '    padding-left: 5px;\n'
            '    padding-top: 5px;\n'
            '}\n'
            '',
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/pause_icon.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_pause.setIcon(icon3)
        self.btn_pause.setIconSize(QtCore.QSize(30, 35))
        self.btn_pause.setObjectName('btn_pause')
        self.horizontalLayout_10.addWidget(self.btn_pause)
        self.btn_clear = QtWidgets.QPushButton(self.frame_btn_2)
        self.btn_clear.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet(
            'QPushButton#btn_clear\n'
            '{\n'
            '   background-color: rgba(255, 255, 255, 0.4);\n'
            '    color: white;\n'
            '    border-radius: 15px;\n'
            '    border: 2px solid white;\n'
            '}\n'
            'QPushButton:hover#btn_clear\n'
            '{\n'
            '   background-color: lightblue\n'
            '}\n'
            'QPushButton:pressed#btn_clear\n'
            '{\n'
            '    background-color: white;\n'
            '    color: black;\n'
            '    padding-left: 5px;\n'
            '    padding-top: 5px;\n'
            '}',
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/clear_icon.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_clear.setIcon(icon4)
        self.btn_clear.setIconSize(QtCore.QSize(30, 35))
        self.btn_clear.setObjectName('btn_clear')
        self.horizontalLayout_10.addWidget(self.btn_clear)
        self.verticalLayout_3.addWidget(
            self.frame_btn_2, 0, QtCore.Qt.AlignTop,
        )
        self.verticalLayout_6.addWidget(self.frame_buttons)
        self.horizontalLayout.addWidget(self.fr_main_functions)
        self.widget_input = QtWidgets.QWidget(self.frame_input)
        self.widget_input.setObjectName('widget_input')
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_input)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName('verticalLayout_5')
        self.label_input = QtWidgets.QLabel(self.widget_input)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_input.sizePolicy().hasHeightForWidth(),
        )
        self.label_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_input.setFont(font)
        self.label_input.setStyleSheet('background: rgba(255, 255, 255, 0.8)')
        self.label_input.setFrameShape(QtWidgets.QFrame.Box)
        self.label_input.setLineWidth(2)
        self.label_input.setScaledContents(True)
        self.label_input.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input.setObjectName('label_input')
        self.verticalLayout_5.addWidget(self.label_input)
        self.horizontalLayout.addWidget(self.widget_input)
        self.gridLayout_4.addWidget(self.frame_input, 0, 0, 1, 1)
        self.frame_output = QtWidgets.QFrame(self.home_page)
        self.frame_output.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_output.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_output.setObjectName('frame_output')
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_output)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName('horizontalLayout_9')
        self.widget_result1 = QtWidgets.QWidget(self.frame_output)
        self.widget_result1.setStyleSheet(
            'color: white;\n'
            'border-radius: 15px;\n'
            'border: 2px solid lightgray;',
        )
        self.widget_result1.setObjectName('widget_result1')
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_result1)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName('verticalLayout_12')
        self.fr_info_result1 = QtWidgets.QFrame(self.widget_result1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.fr_info_result1.sizePolicy().hasHeightForWidth(),
        )
        self.fr_info_result1.setSizePolicy(sizePolicy)
        self.fr_info_result1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_info_result1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_info_result1.setObjectName('fr_info_result1')
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fr_info_result1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.widget_img_result1 = QtWidgets.QWidget(self.fr_info_result1)
        self.widget_img_result1.setObjectName('widget_img_result1')
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_img_result1)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName('verticalLayout_10')
        self.label_img_result1 = QtWidgets.QLabel(self.widget_img_result1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_img_result1.sizePolicy().hasHeightForWidth(),
        )
        self.label_img_result1.setSizePolicy(sizePolicy)
        self.label_img_result1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img_result1.setText('')
        self.label_img_result1.setPixmap(
            QtGui.QPixmap('E:/Qt_Designer/fire_icon.jpg'),
        )
        self.label_img_result1.setScaledContents(True)
        self.label_img_result1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_result1.setObjectName('label_img_result1')
        self.verticalLayout_10.addWidget(self.label_img_result1)
        self.horizontalLayout_3.addWidget(self.widget_img_result1)
        self.widget_info_result1 = QtWidgets.QWidget(self.fr_info_result1)
        self.widget_info_result1.setObjectName('widget_info_result1')
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(
            self.widget_info_result1,
        )
        self.verticalLayout_11.setObjectName('verticalLayout_11')
        self.label_name_result1 = QtWidgets.QLabel(self.widget_info_result1)
        self.label_name_result1.setObjectName('label_name_result1')
        self.verticalLayout_11.addWidget(self.label_name_result1)
        self.label_born_result1 = QtWidgets.QLabel(self.widget_info_result1)
        self.label_born_result1.setStyleSheet('color: white')
        self.label_born_result1.setScaledContents(True)
        self.label_born_result1.setObjectName('label_born_result1')
        self.verticalLayout_11.addWidget(self.label_born_result1)
        self.label_HKTT_result1 = QtWidgets.QLabel(self.widget_info_result1)
        self.label_HKTT_result1.setObjectName('label_HKTT_result1')
        self.verticalLayout_11.addWidget(self.label_HKTT_result1)
        self.label_class_result1 = QtWidgets.QLabel(self.widget_info_result1)
        self.label_class_result1.setStyleSheet('color: white')
        self.label_class_result1.setScaledContents(True)
        self.label_class_result1.setObjectName('label_class_result1')
        self.verticalLayout_11.addWidget(self.label_class_result1)
        self.label_course_result1 = QtWidgets.QLabel(self.widget_info_result1)
        self.label_course_result1.setStyleSheet('color: white')
        self.label_course_result1.setScaledContents(True)
        self.label_course_result1.setObjectName('label_course_result1')
        self.verticalLayout_11.addWidget(self.label_course_result1)
        self.label_MSV_result1 = QtWidgets.QLabel(self.widget_info_result1)
        self.label_MSV_result1.setObjectName('label_MSV_result1')
        self.verticalLayout_11.addWidget(self.label_MSV_result1)
        self.horizontalLayout_3.addWidget(self.widget_info_result1)
        self.verticalLayout_12.addWidget(self.fr_info_result1)
        self.horizontalLayout_9.addWidget(self.widget_result1)
        self.widget_result2 = QtWidgets.QWidget(self.frame_output)
        self.widget_result2.setStyleSheet(
            'border-radius: 15px;\n'
            'border: 2px solid lightgray;',
        )
        self.widget_result2.setObjectName('widget_result2')
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_result2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName('verticalLayout_14')
        self.fr_info_result2 = QtWidgets.QFrame(self.widget_result2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.fr_info_result2.sizePolicy().hasHeightForWidth(),
        )
        self.fr_info_result2.setSizePolicy(sizePolicy)
        self.fr_info_result2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_info_result2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_info_result2.setObjectName('fr_info_result2')
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fr_info_result2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.widget_img_result2 = QtWidgets.QWidget(self.fr_info_result2)
        self.widget_img_result2.setObjectName('widget_img_result2')
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_img_result2)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName('verticalLayout_16')
        self.label_img_result2 = QtWidgets.QLabel(self.widget_img_result2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label_img_result2.sizePolicy().hasHeightForWidth(),
        )
        self.label_img_result2.setSizePolicy(sizePolicy)
        self.label_img_result2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img_result2.setText('')
        self.label_img_result2.setPixmap(
            QtGui.QPixmap('E:/Qt_Designer/fire_icon.jpg'),
        )
        self.label_img_result2.setScaledContents(True)
        self.label_img_result2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_result2.setObjectName('label_img_result2')
        self.verticalLayout_16.addWidget(self.label_img_result2)
        self.horizontalLayout_4.addWidget(self.widget_img_result2)
        self.widget_info_result2 = QtWidgets.QWidget(self.fr_info_result2)
        self.widget_info_result2.setObjectName('widget_info_result2')
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(
            self.widget_info_result2,
        )
        self.verticalLayout_17.setObjectName('verticalLayout_17')
        self.label_name_result2 = QtWidgets.QLabel(self.widget_info_result2)
        self.label_name_result2.setStyleSheet('color: white')
        self.label_name_result2.setScaledContents(True)
        self.label_name_result2.setObjectName('label_name_result2')
        self.verticalLayout_17.addWidget(self.label_name_result2)
        self.label_born_result2 = QtWidgets.QLabel(self.widget_info_result2)
        self.label_born_result2.setStyleSheet('color: white')
        self.label_born_result2.setScaledContents(True)
        self.label_born_result2.setObjectName('label_born_result2')
        self.verticalLayout_17.addWidget(self.label_born_result2)
        self.label_HKTT_result2 = QtWidgets.QLabel(self.widget_info_result2)
        self.label_HKTT_result2.setStyleSheet('color: white')
        self.label_HKTT_result2.setScaledContents(True)
        self.label_HKTT_result2.setObjectName('label_HKTT_result2')
        self.verticalLayout_17.addWidget(self.label_HKTT_result2)
        self.label_class_result2 = QtWidgets.QLabel(self.widget_info_result2)
        self.label_class_result2.setStyleSheet('color: white')
        self.label_class_result2.setScaledContents(True)
        self.label_class_result2.setObjectName('label_class_result2')
        self.verticalLayout_17.addWidget(self.label_class_result2)
        self.label_course_result2 = QtWidgets.QLabel(self.widget_info_result2)
        self.label_course_result2.setStyleSheet('color: white')
        self.label_course_result2.setScaledContents(True)
        self.label_course_result2.setObjectName('label_course_result2')
        self.verticalLayout_17.addWidget(self.label_course_result2)
        self.label_MSV_result2 = QtWidgets.QLabel(self.widget_info_result2)
        self.label_MSV_result2.setStyleSheet('color: white')
        self.label_MSV_result2.setScaledContents(True)
        self.label_MSV_result2.setObjectName('label_MSV_result2')
        self.verticalLayout_17.addWidget(self.label_MSV_result2)
        self.horizontalLayout_4.addWidget(self.widget_info_result2)
        self.verticalLayout_14.addWidget(self.fr_info_result2)
        self.horizontalLayout_9.addWidget(self.widget_result2)
        self.gridLayout_4.addWidget(self.frame_output, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.home_page)
        self.maps_page = QtWidgets.QWidget()
        self.maps_page.setObjectName('maps_page')
        self.gridLayout_5 = QtWidgets.QGridLayout(self.maps_page)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName('gridLayout_5')
        self.frame_maps_body = QtWidgets.QFrame(self.maps_page)
        self.frame_maps_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_maps_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_maps_body.setObjectName('frame_maps_body')
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_maps_body)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName('gridLayout_6')
        self.webEV_maps = QtWebEngineWidgets.QWebEngineView(
            self.frame_maps_body,
        )
        self.webEV_maps.setProperty('url', QtCore.QUrl('about:blank'))
        self.webEV_maps.setObjectName('webEV_maps')
        self.gridLayout_6.addWidget(self.webEV_maps, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_maps_body, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.maps_page)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_main_body, 0, 1, 1, 1)
        self.frame_sidebar = QtWidgets.QFrame(self.centralwidget)
        self.frame_sidebar.setMinimumSize(QtCore.QSize(75, 0))
        self.frame_sidebar.setMaximumSize(QtCore.QSize(75, 16777215))
        self.frame_sidebar.setStyleSheet('background-color: black;')
        self.frame_sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sidebar.setObjectName('frame_sidebar')
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_sidebar)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName('gridLayout_3')
        self.label_hide_item = QtWidgets.QLabel(self.frame_sidebar)
        self.label_hide_item.setText('')
        self.label_hide_item.setObjectName('label_hide_item')
        self.gridLayout_3.addWidget(self.label_hide_item, 3, 0, 1, 1)
        self.btn_maps = QtWidgets.QPushButton(self.frame_sidebar)
        self.btn_maps.setStyleSheet('background-color: gray;')
        self.btn_maps.setText('')
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/maps_icon.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_maps.setIcon(icon5)
        self.btn_maps.setIconSize(QtCore.QSize(50, 45))
        self.btn_maps.setObjectName('btn_maps')
        self.gridLayout_3.addWidget(self.btn_maps, 2, 0, 1, 1)
        self.btn_home = QtWidgets.QPushButton(self.frame_sidebar)
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setStyleSheet('background-color: gray;')
        self.btn_home.setText('')
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap('E:/Qt_Designer/home_icon.png'),
            QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_home.setIcon(icon6)
        self.btn_home.setIconSize(QtCore.QSize(50, 45))
        self.btn_home.setObjectName('btn_home')
        self.gridLayout_3.addWidget(self.btn_home, 1, 0, 1, 1)
        self.btn_setting = QtWidgets.QPushButton(self.frame_sidebar)
        self.btn_setting.setStyleSheet('background-color: gray;')
        self.btn_setting.setText('')
        icon7 = QtGui.QIcon()
        icon7.addPixmap(
            QtGui.QPixmap(
                'E:/Qt_Designer/setting_icon.png',
            ), QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_setting.setIcon(icon7)
        self.btn_setting.setIconSize(QtCore.QSize(50, 45))
        self.btn_setting.setObjectName('btn_setting')
        self.gridLayout_3.addWidget(self.btn_setting, 4, 0, 1, 1)
        self.btn_sidebar = QtWidgets.QPushButton(self.frame_sidebar)
        self.btn_sidebar.setStyleSheet('background-color: gray;')
        self.btn_sidebar.setText('')
        icon8 = QtGui.QIcon()
        icon8.addPixmap(
            QtGui.QPixmap(
                'E:/Qt_Designer/sidebar_icon.png',
            ), QtGui.QIcon.Normal, QtGui.QIcon.Off,
        )
        self.btn_sidebar.setIcon(icon8)
        self.btn_sidebar.setIconSize(QtCore.QSize(50, 40))
        self.btn_sidebar.setObjectName('btn_sidebar')
        self.gridLayout_3.addWidget(self.btn_sidebar, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_sidebar, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'MainWindow'))
        self.le_cam_path.setPlaceholderText(
            _translate('MainWindow', 'Add Path Video Here'),
        )
        self.btn_choose_path.setText(_translate('MainWindow', ' Choose Path'))
        self.btn_start.setText(_translate('MainWindow', ' Process'))
        self.btn_link_cam.setText(_translate('MainWindow', 'Camera'))
        self.btn_pause.setText(_translate('MainWindow', ' Pause'))
        self.btn_clear.setText(_translate('MainWindow', ' Clear'))
        self.label_input.setText(_translate('MainWindow', 'Input Image'))
        self.label_name_result1.setText(_translate('MainWindow', 'Họ tên'))
        self.label_born_result1.setText(_translate('MainWindow', 'Ngày sinh'))
        self.label_HKTT_result1.setText(_translate('MainWindow', 'HKTT'))
        self.label_class_result1.setText(_translate('MainWindow', 'Lớp'))
        self.label_course_result1.setText(_translate('MainWindow', 'Khóa học'))
        self.label_MSV_result1.setText(_translate('MainWindow', 'Mã SV'))
        self.label_name_result2.setText(_translate('MainWindow', 'Họ tên'))
        self.label_born_result2.setText(_translate('MainWindow', 'Ngày sinh'))
        self.label_HKTT_result2.setText(_translate('MainWindow', 'HKTT'))
        self.label_class_result2.setText(_translate('MainWindow', 'Lớp'))
        self.label_course_result2.setText(_translate('MainWindow', 'Khóa học'))
        self.label_MSV_result2.setText(_translate('MainWindow', 'Mã SV'))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
